### ISSUE TITLE
Printed pdf is not showing in dutch language

### ISSUE THREAD

**Issue by deepak-netwin** [fooman/printorderpdf-m2#6]
Hi,

I've 2 stores on my website i.e. english and dutch. 
I've printed orders of dutch stores however it shows everything in english. I think it should translate all the words to dutch. I've already updated nl_NL.csv in the extension folder but still no luck.

Can you please let me know how can I handle translations in pdf?

Best Regards,
Deepak

**Comment by deepak-netwin** [comment]
Hi, I'm still waiting for your reply.

**Comment by deepak-netwin** [comment]
Any updates?

**Comment by fooman** [comment]
This extension should exhibit the same behaviour as Magento does when printing the invoice pdf. The pdf is in the locale that you have selected for your user. So if the rest of the admin is showing in English the pdf will be in English as well, and vice versa if you are seeing Dutch in the admin the pdf is also Dutch.

As we are using the same approach as Magento I suggest filing a feature request with Magento and once the behaviour changes we will follow suite. Feel free to re-open this ticket if the behaviour of the order pdf is different to the invoice pdf.
