### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by honeymobiweb** [fooman/printorderpdf-m2#8]
i am getting problem in this extension. when i print order ,it not supported arabic language(RTL) like magento default print functinalitycan you please help me for that??

**Comment by fooman** [comment]
@honeymobiweb are you sure this is with a default Magento install? Generally our extension builds on top of the original Magento invoice (see [here](https://github.com/fooman/printorderpdf-m2/blob/develop/src/Model/Pdf/Order.php#L14)). 

Can you post the order pdf as well your invoice pdf somewhere to download to compare?

**Comment by fooman** [comment]
Closing due to no response - feel free to re-open.
